//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public class CHUCNANG
    { 
        public int MaChucNang { get; set; }
        public string TenChucNang { get; set; }
        public virtual ICollection<QUYENHANNGUOIDUNG> QUYENHANNGUOIDUNGs { get; set; }
        public virtual ICollection<QUYENHANLOAINGUOIDUNG> QUYENHANLOAINGUOIDUNGs { get; set; }
    }
}
