//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBanHang.Models
{
    using System;
    using System.Collections.Generic;
    public class DONDATHANG
    {
        public int MaDDH { get; set; }
        public DateTime ThoiDiemDat { get; set; }
        public int TinhTrangGiaoHang { get; set; }
        public DateTime ThoiDiemLap { get; set; }
        public DateTime NgayGiaoDuKien { get; set; }
        public int UuDai { get; set; }
        public decimal TongTien { get; set; }
        public int MaNV { get; set; }
        public int MaKH { get; set; }
        public int MaGioHang { get; set; }
        public decimal PhiVanChuyen { get; set; }
        public virtual ICollection<CHITIETDONDATHANG> CHITIETDONDATHANGs { get; set; }
        public virtual GIOHANG GIOHANG { get; set; }
    }
}
