//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public class GIOHANG
    {
        public int MaGioHang { get; set; }
        public int MaKH { get; set; }
        public decimal ThanhTien { get; set; }
        public bool DaDat { get; set; }
        public virtual ICollection<CHITIETGIOHANG> CHITIETGIOHANGs { get; set; }
        public virtual ICollection<DONDATHANG> DONDATHANGs { get; set; }
        public virtual LOAINGUOIDUNG NGUOIDUNG { get; set; }
    }
}
