//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using WebApplication1.Models;
using System.Linq;
using System.Web;


namespace WebApplication1.Models
{
    

    public class LOAINGUOIDUNG
    {
        public int MaLoaiNguoiDung { get; set; }
        public string TenLoaiNguoiDung { get; set; }
        public virtual ICollection<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public virtual ICollection<QUYENHANLOAINGUOIDUNG> QUYENHANLOAINGUOIDUNGs { get; set; }
        public LOAINGUOIDUNG(DataRow row)
        {

        }
    }
}
